services:
  auth-service:
    image: 
    ports:
      -"5541:5541"
    networks:
      - haavops
    
  user-service:
    image:
    ports:
      -"5542:5542"
    networks:
      - haavops
  

  ## nginx goes here, sammen med config filen