user nginx;

events {
    worker_connections 1000;
}
http {

    upstream userservices {
        server user-service:8080;
    }

    upstream catalogservices {
        server catalog-service:8080;
    }

    upstream orderservices {
        server order-service:8080;
    }

    server {
            listen 4000;
            server_name catalogservices;
            location /catalogs/ {
                proxy_pass http://catalogservices/;
            }

            location /users/ {
                proxy_pass http://userservices/;
            }

            location /orders/ {
                proxy_pass http://orderservices/;
            }
    }
}